### ISSUE TITLE
Add 'http://' in front of url if it doesn't start with 'http://' or 'https://'

### ISSUE THREAD

**Issue by milanico2309** [laurensk/Dockmon#1] opened 2021-02-23 21:18 UTC
For some reason the app is not working for me. I have Docker and Portainer running on a RaspberryPi. When I try to login from the app, I press the login button but nothing happens, I remain on the login screen.

If I intentionally enter incorrect data into the login-form, I get an error message, so some kind of validation and therefore communication with my pi is happening...

**Comment by laurensk** [comment] 2021-02-24 08:27
Hey @milanico2309! Thanks for reaching out. I've just tested Dockmon with the newest Portainer build running on my server and everything seems to work fine. I guess the problem is not related to Dockmon itself, but I'll help you fix your issue!

Are you using an IP-address of your local network to connect to the ip?

**Comment by milanico2309** [comment] 2021-02-24 08:42
Hey, thanks for the quick reply!!! I tried both. When using the IP Address i get an error-message, when using the host name I get nothing... (see attached screenshots)!

![image](https://user-images.githubusercontent.com/34548427/108973029-37459600-7684-11eb-80db-e23f49199a75.png)
![image](https://user-images.githubusercontent.com/34548427/108973066-40366780-7684-11eb-851c-b9d557927020.png)
![image](https://user-images.githubusercontent.com/34548427/108973872-29dcdb80-7685-11eb-97b8-c102c67bb5b6.png)
![image](https://user-images.githubusercontent.com/34548427/108973262-71169c80-7684-11eb-8b0a-17ff90e8144f.png)

(I just noticed, that iPhone shows the password field as empty when making a screenshot... neat)

**Comment by laurensk** [comment] 2021-02-24 08:45
Hi! Thanks for your quick response too! Can you try putting "http://" before your ip?

**Comment by shoaei** [comment] 2021-03-05 12:46
Yep, the “http://“ was missing and now it works for me too. Thanks.

**Comment by laurensk** [comment] 2021-03-05 19:33
Thanks for reporting this issue. I'll add some logic to prevent this from happening to other users.

**Comment by laurensk** [comment] 2021-03-07 15:00
Fixed in version 1.0.1

**Closed as completed** 2021-03-07 14:59 UTC
